kind: pipeline
name: default
clone:
  disable: true
steps:
  - name: clone
    image: alpine/git
    commands:
    - git clone http://172.28.24.205:9999/liwei123/mcc-drone-demo-java.git .
  - name: build
    image: maven:3-jdk-11
    volumes:
    - name: maven-cache
      path: /root/.m2
    commands:
      - ls -al ~/.
      - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - name: notify
    image: drillster/drone-email
    settings:
      from.address: mccservice@mcc2gs.com
      host: smtp.feishu.cn
      port: 465
      username:
        from_secret: email_username
      password: 12345
        from_secret: email_password
      recipients:
        - wei9.li@changhong.com
volumes:
  - name: maven-cache
    host:
      path: /var/lib/cache